<?php

namespace Database\Seeders;

use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $products = [
            // Digital Marketing Products
            [
                'name' => 'Complete Digital Marketing Masterclass',
                'slug' => 'complete-digital-marketing-masterclass',
                'description' => 'Comprehensive digital marketing course covering SEO, SEM, social media, and analytics.',
                'detailed_description' => 'This masterclass includes 50+ hours of video content, practical exercises, case studies, and lifetime access. Learn from industry experts with real-world experience. Topics include: SEO fundamentals, Google Ads, Facebook/Instagram advertising, content marketing, email marketing, analytics and reporting, conversion rate optimization, and more.',
                'price' => 199.99,
                'compare_price' => 299.99,
                'stock' => 1000,
                'digital' => true,
                'category' => 'Digital Marketing',
                'tags' => ['marketing', 'seo', 'social-media', 'advertising', 'course'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/digital-marketing-course.zip',
                'preview_url' => 'https://example.com/preview/digital-marketing-demo',
                'published_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SEO Toolkit Pro',
                'slug' => 'seo-toolkit-pro',
                'description' => 'Professional SEO analysis and optimization toolkit.',
                'detailed_description' => 'Advanced SEO toolkit with keyword research, competitor analysis, backlink monitoring, and rank tracking features. Includes automated reporting, custom dashboards, and API access for integration with other tools.',
                'price' => 79.99,
                'compare_price' => 129.99,
                'stock' => 500,
                'digital' => true,
                'category' => 'Digital Marketing',
                'tags' => ['seo', 'analytics', 'keywords', 'backlinks', 'tool'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/seo-toolkit.zip',
                'preview_url' => 'https://example.com/preview/seo-toolkit-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Web Development Products
            [
                'name' => 'React Admin Dashboard Template',
                'slug' => 'react-admin-dashboard-template',
                'description' => 'Modern React admin dashboard with 200+ components and pages.',
                'detailed_description' => 'Complete admin dashboard built with React, TypeScript, and Material-UI. Features include: 200+ reusable components, 50+ pages, dark/light themes, responsive design, charts and graphs, data tables, forms, authentication pages, and comprehensive documentation.',
                'price' => 49.99,
                'compare_price' => 89.99,
                'stock' => 200,
                'digital' => true,
                'category' => 'Web Development',
                'tags' => ['react', 'dashboard', 'admin', 'template', 'typescript'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/react-dashboard.zip',
                'preview_url' => 'https://example.com/preview/react-dashboard-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Laravel E-commerce Package',
                'slug' => 'laravel-ecommerce-package',
                'description' => 'Complete e-commerce solution for Laravel applications.',
                'detailed_description' => 'Full-featured e-commerce package with shopping cart, payment processing, inventory management, order tracking, and admin panel. Supports multiple payment gateways, shipping methods, tax calculations, and includes API endpoints for mobile apps.',
                'price' => 149.99,
                'compare_price' => 199.99,
                'stock' => 150,
                'digital' => true,
                'category' => 'Web Development',
                'tags' => ['laravel', 'ecommerce', 'php', 'package', 'shopping-cart'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/laravel-ecommerce.zip',
                'preview_url' => 'https://example.com/preview/laravel-ecommerce-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Graphic Design Products
            [
                'name' => 'Brand Identity Design Kit',
                'slug' => 'brand-identity-design-kit',
                'description' => 'Complete brand identity package with logos, business cards, and stationery.',
                'detailed_description' => 'Professional brand identity kit including: Logo variations (5 formats), Business card designs (3 layouts), Letterhead and envelope templates, Social media profile images, Brand guidelines document, and source files in AI, EPS, and PNG formats.',
                'price' => 89.99,
                'compare_price' => 149.99,
                'stock' => 300,
                'digital' => true,
                'category' => 'Graphic Design',
                'tags' => ['branding', 'logo', 'identity', 'business-cards', 'stationery'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/brand-kit.zip',
                'preview_url' => 'https://example.com/preview/brand-kit-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Social Media Post Templates',
                'slug' => 'social-media-post-templates',
                'description' => '500+ customizable social media post templates for all platforms.',
                'detailed_description' => 'Extensive collection of social media templates including: Instagram posts and stories, Facebook covers and posts, Twitter headers, LinkedIn banners, YouTube thumbnails, Pinterest pins, and TikTok graphics. All templates are fully customizable with Adobe Photoshop and Illustrator files.',
                'price' => 39.99,
                'compare_price' => 69.99,
                'stock' => 400,
                'digital' => true,
                'category' => 'Graphic Design',
                'tags' => ['social-media', 'templates', 'instagram', 'facebook', 'graphics'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/social-templates.zip',
                'preview_url' => 'https://example.com/preview/social-templates-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Business Tools
            [
                'name' => 'Project Management Dashboard',
                'slug' => 'project-management-dashboard',
                'description' => 'Comprehensive project management software with team collaboration features.',
                'detailed_description' => 'Full-featured project management application with task tracking, time logging, team collaboration, reporting, and integration capabilities. Includes Gantt charts, Kanban boards, resource management, and mobile app access.',
                'price' => 29.99,
                'compare_price' => 49.99,
                'stock' => 250,
                'digital' => true,
                'category' => 'Business Tools',
                'tags' => ['project-management', 'teamwork', 'productivity', 'kanban', 'gantt'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/pm-dashboard.zip',
                'preview_url' => 'https://example.com/preview/pm-dashboard-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Education
            [
                'name' => 'Python Programming Bootcamp',
                'slug' => 'python-programming-bootcamp',
                'description' => 'Complete Python programming course for beginners to advanced learners.',
                'detailed_description' => 'Comprehensive Python programming bootcamp covering: Basic syntax, data structures, object-oriented programming, web development with Django, data analysis with pandas, machine learning basics, and real-world projects. Includes 100+ coding exercises and quizzes.',
                'price' => 99.99,
                'compare_price' => 149.99,
                'stock' => 600,
                'digital' => true,
                'category' => 'Education',
                'tags' => ['python', 'programming', 'coding', 'django', 'data-analysis'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/python-bootcamp.zip',
                'preview_url' => 'https://example.com/preview/python-bootcamp-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'UI/UX Design Masterclass',
                'slug' => 'ui-ux-design-masterclass',
                'description' => 'Complete UI/UX design course with Figma, Adobe XD, and design principles.',
                'detailed_description' => 'Comprehensive UI/UX design masterclass covering: User research and personas, wireframing and prototyping, visual design principles, usability testing, design systems, mobile and web design, accessibility, and portfolio development. Includes 60+ design projects, Figma templates, and industry insights.',
                'price' => 129.99,
                'compare_price' => 189.99,
                'stock' => 450,
                'digital' => true,
                'category' => 'Education',
                'tags' => ['ui-ux', 'design', 'figma', 'prototyping', 'usability'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/ui-ux-masterclass.zip',
                'preview_url' => 'https://example.com/preview/ui-ux-masterclass-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Photography
            [
                'name' => 'Premium Stock Photo Collection',
                'slug' => 'premium-stock-photo-collection',
                'description' => 'High-quality stock photo collection with 10,000+ images.',
                'detailed_description' => 'Extensive stock photo library including: Business and corporate images, lifestyle and people photos, nature and landscapes, technology and gadgets, food and beverages, travel and tourism, and abstract concepts. All images are high-resolution (up to 8K) and royalty-free.',
                'price' => 199.99,
                'compare_price' => 299.99,
                'stock' => 100,
                'digital' => true,
                'category' => 'Photography',
                'tags' => ['stock-photos', 'royalty-free', 'high-resolution', 'business', 'lifestyle'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/stock-photos.zip',
                'preview_url' => 'https://example.com/preview/stock-photos-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Music & Audio
            [
                'name' => 'Professional Sound Effects Library',
                'slug' => 'professional-sound-effects-library',
                'description' => '5,000+ high-quality sound effects for media production.',
                'detailed_description' => 'Comprehensive sound effects library including: Nature sounds, urban environments, household items, animals, transportation, electronics, human sounds, and special effects. All files are in WAV and MP3 formats with metadata tagging.',
                'price' => 79.99,
                'compare_price' => 119.99,
                'stock' => 350,
                'digital' => true,
                'category' => 'Music & Audio',
                'tags' => ['sound-effects', 'audio', 'wav', 'mp3', 'production'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/sound-effects.zip',
                'preview_url' => 'https://example.com/preview/sound-effects-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Video & Animation
            [
                'name' => 'After Effects Animation Pack',
                'slug' => 'after-effects-animation-pack',
                'description' => '100+ After Effects animation presets and templates.',
                'detailed_description' => 'Professional animation pack for Adobe After Effects including: Text animations, logo stings, transitions, particle effects, light effects, and complete project templates. All presets are customizable and include tutorial videos.',
                'price' => 59.99,
                'compare_price' => 99.99,
                'stock' => 180,
                'digital' => true,
                'category' => 'Video & Animation',
                'tags' => ['after-effects', 'animation', 'motion-graphics', 'presets', 'templates'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/ae-animations.zip',
                'preview_url' => 'https://example.com/preview/ae-animations-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Software & Apps
            [
                'name' => 'Task Management Mobile App',
                'slug' => 'task-management-mobile-app',
                'description' => 'Cross-platform mobile app for task and project management.',
                'detailed_description' => 'Complete mobile application for iOS and Android with features including: Task creation and management, project organization, team collaboration, deadline tracking, notifications, cloud sync, and offline support. Includes source code and build files.',
                'price' => 299.99,
                'compare_price' => 399.99,
                'stock' => 50,
                'digital' => true,
                'category' => 'Software & Apps',
                'tags' => ['mobile-app', 'task-management', 'ios', 'android', 'source-code'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/task-app.zip',
                'preview_url' => 'https://example.com/preview/task-app-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Templates
            [
                'name' => 'WordPress Theme Bundle',
                'slug' => 'wordpress-theme-bundle',
                'description' => '20 premium WordPress themes with lifetime updates.',
                'detailed_description' => 'Professional WordPress theme bundle including: Business and corporate themes, portfolio websites, e-commerce shops, blogs, magazines, and niche-specific designs. All themes are responsive, SEO optimized, and include theme options, custom widgets, and documentation.',
                'price' => 179.99,
                'compare_price' => 249.99,
                'stock' => 120,
                'digital' => true,
                'category' => 'Templates',
                'tags' => ['wordpress', 'themes', 'responsive', 'seo', 'premium'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/wp-themes.zip',
                'preview_url' => 'https://example.com/preview/wp-themes-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],

            // Local Market Trending Products
            [
                'name' => 'Local Business Website Template',
                'slug' => 'local-business-website-template',
                'description' => 'Responsive website template designed for local businesses.',
                'detailed_description' => 'Modern website template perfect for local businesses including restaurants, salons, clinics, and retail stores. Features contact forms, service listings, Google Maps integration, and mobile-optimized design.',
                'price' => 49.99,
                'compare_price' => 79.99,
                'stock' => 300,
                'digital' => true,
                'category' => 'Templates',
                'tags' => ['local-business', 'website', 'responsive', 'contact-form', 'maps'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/local-business-template.zip',
                'preview_url' => 'https://example.com/preview/local-business-template-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local SEO Mastery Course',
                'slug' => 'local-seo-mastery-course',
                'description' => 'Complete course on dominating local search results.',
                'detailed_description' => 'Comprehensive local SEO training covering Google My Business optimization, local keyword research, citation building, review management, and local link building strategies. Includes templates and checklists.',
                'price' => 89.99,
                'compare_price' => 129.99,
                'stock' => 200,
                'digital' => true,
                'category' => 'Digital Marketing',
                'tags' => ['local-seo', 'google-my-business', 'citations', 'reviews', 'local-search'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/local-seo-course.zip',
                'preview_url' => 'https://example.com/preview/local-seo-course-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Restaurant Menu Design Pack',
                'slug' => 'restaurant-menu-design-pack',
                'description' => 'Professional menu designs for restaurants and cafes.',
                'detailed_description' => 'Complete menu design package including digital menu boards, printed menu layouts, food photography templates, and branding elements. Compatible with all major design software.',
                'price' => 39.99,
                'compare_price' => 69.99,
                'stock' => 150,
                'digital' => true,
                'category' => 'Graphic Design',
                'tags' => ['restaurant', 'menu-design', 'food', 'branding', 'print'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/menu-design-pack.zip',
                'preview_url' => 'https://example.com/preview/menu-design-pack-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Event Promotion Toolkit',
                'slug' => 'local-event-promotion-toolkit',
                'description' => 'Complete toolkit for promoting local events and gatherings.',
                'detailed_description' => 'Event promotion package including social media graphics, email templates, flyer designs, poster layouts, and event website templates. Perfect for community events, festivals, and local businesses.',
                'price' => 59.99,
                'compare_price' => 99.99,
                'stock' => 180,
                'digital' => true,
                'category' => 'Graphic Design',
                'tags' => ['events', 'promotion', 'social-media', 'flyers', 'community'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/event-promotion-toolkit.zip',
                'preview_url' => 'https://example.com/preview/event-promotion-toolkit-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Small Business Accounting Software',
                'slug' => 'small-business-accounting-software',
                'description' => 'User-friendly accounting software for small local businesses.',
                'detailed_description' => 'Complete accounting solution with invoicing, expense tracking, tax preparation, financial reporting, and inventory management. Cloud-based with mobile app access.',
                'price' => 29.99,
                'compare_price' => 49.99,
                'stock' => 250,
                'digital' => true,
                'category' => 'Business Tools',
                'tags' => ['accounting', 'small-business', 'invoicing', 'taxes', 'cloud'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/accounting-software.zip',
                'preview_url' => 'https://example.com/preview/accounting-software-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Market Research Report',
                'slug' => 'local-market-research-report',
                'description' => 'Comprehensive market research for local business opportunities.',
                'detailed_description' => 'Detailed market research report including competitor analysis, customer demographics, spending patterns, and growth opportunities for local markets. Includes data visualizations and actionable insights.',
                'price' => 199.99,
                'compare_price' => 299.99,
                'stock' => 100,
                'digital' => true,
                'category' => 'Business Tools',
                'tags' => ['market-research', 'local-business', 'demographics', 'competitor-analysis', 'data'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/market-research-report.pdf',
                'preview_url' => 'https://example.com/preview/market-research-report-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Community Newsletter Template',
                'slug' => 'community-newsletter-template',
                'description' => 'Professional newsletter template for local communities.',
                'detailed_description' => 'Customizable newsletter template for community organizations, local businesses, and neighborhood associations. Includes event calendars, community news, business spotlights, and member communications.',
                'price' => 24.99,
                'compare_price' => 39.99,
                'stock' => 400,
                'digital' => true,
                'category' => 'Templates',
                'tags' => ['newsletter', 'community', 'local', 'events', 'communication'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/newsletter-template.zip',
                'preview_url' => 'https://example.com/preview/newsletter-template-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Business Social Media Kit',
                'slug' => 'local-business-social-media-kit',
                'description' => 'Complete social media marketing kit for local businesses.',
                'detailed_description' => 'Social media toolkit including profile templates, post graphics, story templates, hashtag strategies, and content calendars specifically designed for local businesses and service providers.',
                'price' => 34.99,
                'compare_price' => 59.99,
                'stock' => 220,
                'digital' => true,
                'category' => 'Digital Marketing',
                'tags' => ['social-media', 'local-business', 'marketing', 'content', 'branding'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/social-media-kit.zip',
                'preview_url' => 'https://example.com/preview/social-media-kit-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Photography Stock Collection',
                'slug' => 'local-photography-stock-collection',
                'description' => 'Stock photos featuring local scenes and community life.',
                'detailed_description' => 'Curated collection of high-quality stock photographs featuring local communities, urban and rural scenes, diverse people, local businesses, and cultural landmarks. Perfect for local marketing and media.',
                'price' => 79.99,
                'compare_price' => 119.99,
                'stock' => 300,
                'digital' => true,
                'category' => 'Photography',
                'tags' => ['stock-photos', 'local', 'community', 'urban', 'cultural'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/local-stock-photos.zip',
                'preview_url' => 'https://example.com/preview/local-stock-photos-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Neighborhood App Development Kit',
                'slug' => 'neighborhood-app-development-kit',
                'description' => 'Development kit for building local community apps.',
                'detailed_description' => 'Complete development kit for creating mobile apps focused on neighborhood communities. Includes UI components, backend templates, community features, and local service integrations.',
                'price' => 149.99,
                'compare_price' => 199.99,
                'stock' => 80,
                'digital' => true,
                'category' => 'Software & Apps',
                'tags' => ['mobile-app', 'community', 'neighborhood', 'development', 'local-services'],
                'featured' => true,
                'active' => true,
                'file_url' => 'https://example.com/downloads/neighborhood-app-kit.zip',
                'preview_url' => 'https://example.com/preview/neighborhood-app-kit-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Business Video Course',
                'slug' => 'local-business-video-course',
                'description' => 'Video training course for starting and growing local businesses.',
                'detailed_description' => 'Comprehensive video course covering business planning, marketing, customer service, financial management, and growth strategies specifically for local entrepreneurs and small business owners.',
                'price' => 69.99,
                'compare_price' => 99.99,
                'stock' => 350,
                'digital' => true,
                'category' => 'Education',
                'tags' => ['business-training', 'entrepreneurship', 'local-business', 'video-course', 'growth'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/local-business-course.zip',
                'preview_url' => 'https://example.com/preview/local-business-course-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Community Event Planning Guide',
                'slug' => 'community-event-planning-guide',
                'description' => 'Complete guide for organizing successful community events.',
                'detailed_description' => 'Step-by-step guide covering event planning, budgeting, marketing, logistics, volunteer management, and post-event follow-up. Includes templates, checklists, and real-world examples.',
                'price' => 19.99,
                'compare_price' => 34.99,
                'stock' => 500,
                'digital' => true,
                'category' => 'Education',
                'tags' => ['event-planning', 'community', 'organization', 'volunteers', 'logistics'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/event-planning-guide.pdf',
                'preview_url' => 'https://example.com/preview/event-planning-guide-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Artisan Marketplace Template',
                'slug' => 'local-artisan-marketplace-template',
                'description' => 'E-commerce template for local artisans and crafters.',
                'detailed_description' => 'Specialized e-commerce website template for local artisans, crafters, and handmade goods sellers. Features product galleries, artist profiles, booking systems, and community showcase sections.',
                'price' => 89.99,
                'compare_price' => 139.99,
                'stock' => 120,
                'digital' => true,
                'category' => 'Templates',
                'tags' => ['ecommerce', 'artisans', 'handmade', 'marketplace', 'crafts'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/artisan-marketplace-template.zip',
                'preview_url' => 'https://example.com/preview/artisan-marketplace-template-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Food Business Starter Kit',
                'slug' => 'local-food-business-starter-kit',
                'description' => 'Complete starter kit for local food businesses.',
                'detailed_description' => 'Comprehensive kit for starting local food businesses including menu templates, branding guides, regulatory compliance checklists, marketing materials, and operational templates for restaurants, cafes, and food trucks.',
                'price' => 49.99,
                'compare_price' => 79.99,
                'stock' => 180,
                'digital' => true,
                'category' => 'Business Tools',
                'tags' => ['food-business', 'restaurants', 'cafes', 'regulatory', 'branding'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/food-business-starter-kit.zip',
                'preview_url' => 'https://example.com/preview/food-business-starter-kit-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Community Podcast Production Kit',
                'slug' => 'community-podcast-production-kit',
                'description' => 'Complete toolkit for creating community-focused podcasts.',
                'detailed_description' => 'Podcast production kit including recording guides, editing templates, show notes formats, audience engagement strategies, and monetization guides specifically for local and community-based content creators.',
                'price' => 44.99,
                'compare_price' => 74.99,
                'stock' => 160,
                'digital' => true,
                'category' => 'Music & Audio',
                'tags' => ['podcast', 'audio', 'community', 'production', 'content-creation'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/podcast-production-kit.zip',
                'preview_url' => 'https://example.com/preview/podcast-production-kit-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Local Real Estate Marketing Bundle',
                'slug' => 'local-real-estate-marketing-bundle',
                'description' => 'Marketing toolkit for local real estate professionals.',
                'detailed_description' => 'Complete marketing bundle for real estate agents including property listing templates, social media content, email campaigns, neighborhood guides, and client presentation materials tailored for local markets.',
                'price' => 79.99,
                'compare_price' => 119.99,
                'stock' => 140,
                'digital' => true,
                'category' => 'Digital Marketing',
                'tags' => ['real-estate', 'marketing', 'property', 'local-market', 'client-presentation'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/real-estate-marketing-bundle.zip',
                'preview_url' => 'https://example.com/preview/real-estate-marketing-bundle-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Small Town Business Growth Course',
                'slug' => 'small-town-business-growth-course',
                'description' => 'Specialized course for growing businesses in small communities.',
                'detailed_description' => 'Focused training course for entrepreneurs in small towns and rural areas covering local marketing strategies, community engagement, online presence, customer retention, and sustainable growth techniques.',
                'price' => 54.99,
                'compare_price' => 89.99,
                'stock' => 220,
                'digital' => true,
                'category' => 'Education',
                'tags' => ['small-business', 'rural', 'community', 'growth', 'entrepreneurship'],
                'featured' => false,
                'active' => true,
                'file_url' => 'https://example.com/downloads/small-town-business-course.zip',
                'preview_url' => 'https://example.com/preview/small-town-business-course-demo',
                'published_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('ProductSeeder completed successfully!');
        $this->command->info('Created ' . count($products) . ' sample products.');
    }
}
